#pragma once

#define IOCTL_ADD_VIRTUAL_DISPLAY CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_REMOVE_VIRTUAL_DISPLAY CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)

typedef struct _VIRTUAL_DISPLAY_PARAMS {
	UINT Width;
	UINT Height;
	UINT RefreshRate;
	GUID MonitorGuid;
	WCHAR DeviceName[14];  // Ensure the length matches your needs
} VIRTUAL_DISPLAY_PARAMS, * PVIRTUAL_DISPLAY_PARAMS;

typedef struct _VIRTUAL_DISPLAY_REMOVE_PARAMS {
	GUID MonitorGuid;  // Identifier for the display to be removed
} VIRTUAL_DISPLAY_REMOVE_PARAMS, * PVIRTUAL_DISPLAY_REMOVE_PARAMS;

typedef struct _VIRTUAL_DISPLAY_OUTPUT {
	UINT ConnectorID;
} VIRTUAL_DISPLAY_OUTPUT, * PVIRTUAL_DISPLAY_OUTPUT;